"""K5 — the human-auditable chunk dump.

Writes ``chunks.txt`` (deliverable D-7): one ``=== CHUNK <chunk_id> ===`` header,
the full metadata block, then the text, then an ``embedding:`` section holding
the 384-dim vector the chunk was embedded to.

The vectors are read back out of the persisted collection, so the dump can never
disagree with what retrieval will search. They are printed to
:data:`VECTOR_PRECISION` decimal places: enough to verify by eye and by test,
without making the file unreadable. ``chroma/`` keeps full float precision and
is the source of truth. ``chunks.jsonl`` stays vector-free on purpose: it is the
machine-readable feed for tests, and 166 x 384 floats would triple its size for
no benefit.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence

from src.ingest.models import Chunk

#: Decimal places used when printing a vector. Display only.
VECTOR_PRECISION = 6

#: Emitted when a chunk has no vector yet, i.e. the store has not been written.
EMBEDDING_MISSING = "(not embedded yet - run: python ingest.py --stage all)"

HEADER = f"""\
# chunks.txt - deliverable D-7, generated by src/ingest/chunk_writer.py (K5)
# Regenerate with: python ingest.py --stage all
#
# One block per chunk: a header line, the metadata the pipeline depends on, a
# separator, the chunk text, then the embedding vector. Vectors are
# sentence-transformers/all-MiniLM-L6-v2, L2-normalised, shown to
# {VECTOR_PRECISION} decimal places for readability; chroma/ holds full precision.
#
# The only percentages in this corpus are fee, tax and ratio facts. There is no
# performance data: see the C-3 check in docs/implementation.md Phase 1.
"""

METADATA_ORDER: Sequence[str] = (
    "source_url",
    "scheme",
    "category",
    "plan_variant",
    "section",
    "fact_type",
    "authority",
    "is_atomic",
    "char_len",
    "source_fetched_at",
    "content_hash",
)


def format_vector(vector: Sequence[float], precision: int = VECTOR_PRECISION) -> str:
    """Render a vector as a bracketed, fixed-precision numeric list."""
    return "[" + ", ".join(f"{float(value):.{precision}f}" for value in vector) + "]"


def render_chunks(
    chunks: Sequence[Chunk], vectors: Optional[Mapping[str, Sequence[float]]] = None
) -> str:
    """Render every chunk as the ``chunks.txt`` body, with its embedding."""
    lookup: Mapping[str, Sequence[float]] = vectors or {}
    blocks: List[str] = []
    for chunk in chunks:
        metadata = chunk.metadata
        lines = [f"=== CHUNK {chunk.chunk_id} ==="]
        for key in METADATA_ORDER:
            if key in metadata:
                lines.append(f"{key}: {metadata[key]}")
        for key in sorted(set(metadata) - set(METADATA_ORDER)):
            lines.append(f"{key}: {metadata[key]}")
        lines.append("---")
        lines.append(chunk.text)
        lines.append("")
        vector = lookup.get(chunk.chunk_id)
        if vector:
            lines.append(f"embedding_dim: {len(vector)}")
            lines.append(f"embedding: {format_vector(vector)}")
        else:
            lines.append(f"embedding: {EMBEDDING_MISSING}")
        blocks.append("\n".join(lines))
    return HEADER + "\n" + "\n\n".join(blocks) + ("\n" if blocks else "")


def write_chunks(
    chunks: Sequence[Chunk],
    txt_path: Path,
    jsonl_path: Path,
    vectors: Optional[Mapping[str, Sequence[float]]] = None,
) -> dict:
    """Write ``chunks.txt`` and ``chunks.jsonl``. Both are regenerated each run."""
    txt_path.parent.mkdir(parents=True, exist_ok=True)
    txt_path.write_text(render_chunks(chunks, vectors), encoding="utf-8")

    jsonl_path.parent.mkdir(parents=True, exist_ok=True)
    with jsonl_path.open("w", encoding="utf-8") as handle:
        for chunk in chunks:
            handle.write(
                json.dumps(
                    {"chunk_id": chunk.chunk_id, "text": chunk.text, **dict(chunk.metadata)},
                    ensure_ascii=False,
                    sort_keys=True,
                )
                + "\n"
            )
    return {
        "chunks_txt": str(txt_path),
        "chunks_jsonl": str(jsonl_path),
        "count": len(chunks),
        "embedded": sum(1 for chunk in chunks if (vectors or {}).get(chunk.chunk_id)),
    }


def read_chunks_jsonl(path: Path) -> List[dict]:
    """Read ``chunks.jsonl`` back, for tests and for the P3 pipeline."""
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]
